# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ProximateiOSSDK' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

	# Pods for ProximateiOSSDK
	pod 'OCMapper', '~> 2.1'
	pod 'DDPageControl', '~> 0.1'
end
